-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\conv_core_ip_src_slicer.vhd
-- Created: 2025-03-05 16:47:12
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: conv_core_ip_src_slicer
-- Source Path: sobelFilter2024a/conv_core/Subsystem1/slicer
-- Hierarchy Level: 2
-- Model version: 8.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY conv_core_ip_src_slicer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        channel_in                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        out_1                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_2                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_3                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_4                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_5                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_6                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_7                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_8                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out_9                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END conv_core_ip_src_slicer;


ARCHITECTURE rtl OF conv_core_ip_src_slicer IS

  -- Component Declarations
  COMPONENT conv_core_ip_src_SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : conv_core_ip_src_SimpleDualPortRAM_generic
    USE ENTITY work.conv_core_ip_src_SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL channel_in_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay1_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL mergedDelay_waddr                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL mergedDelay_wrenb                : std_logic;  -- ufix1
  SIGNAL mergedDelay_raddr                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Line_buffer_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay2_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay5_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL mergedInput                      : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL mergedDelay_regin                : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL mergedDelay_regout               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL mergedDelay_regout_unsigned      : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL mergedOutput                     : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL slicedInput                      : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL slicedInput_1                    : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Line_buffer1_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay3_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay6_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_ShiftRegisterRAM_generic : conv_core_ip_src_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 16
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => std_logic_vector(mergedDelay_regin),
              wr_addr => std_logic_vector(mergedDelay_waddr),
              wr_en => mergedDelay_wrenb,  -- ufix1
              rd_addr => std_logic_vector(mergedDelay_raddr),
              dout => mergedDelay_regout
              );

  channel_in_unsigned <= unsigned(channel_in);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay1_out1 <= channel_in_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  out_2 <= std_logic_vector(Delay1_out1);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay4_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  out_3 <= std_logic_vector(Delay4_out1);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 747
  -- Write address counter for RAM-based shift register mergedDelay
  mergedDelay_wr_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        mergedDelay_waddr <= to_unsigned(16#000#, 10);
      ELSIF enb = '1' THEN
        IF mergedDelay_waddr >= to_unsigned(16#2EB#, 10) THEN 
          mergedDelay_waddr <= to_unsigned(16#000#, 10);
        ELSE 
          mergedDelay_waddr <= mergedDelay_waddr + to_unsigned(16#001#, 10);
        END IF;
      END IF;
    END IF;
  END PROCESS mergedDelay_wr_process;


  mergedDelay_wrenb <= '1';

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 747
  -- Read address counter for RAM-based shift register mergedDelay
  mergedDelay_rd_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        mergedDelay_raddr <= to_unsigned(16#001#, 10);
      ELSIF enb = '1' THEN
        IF mergedDelay_raddr >= to_unsigned(16#2EB#, 10) THEN 
          mergedDelay_raddr <= to_unsigned(16#000#, 10);
        ELSE 
          mergedDelay_raddr <= mergedDelay_raddr + to_unsigned(16#001#, 10);
        END IF;
      END IF;
    END IF;
  END PROCESS mergedDelay_rd_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay2_out1 <= Line_buffer_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay5_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  mergedInput <= Delay4_out1 & Delay5_out1;

  -- Input register for RAM-based shift register mergedDelay
  mergedDelay_reginc_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        mergedDelay_regin <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        mergedDelay_regin <= mergedInput;
      END IF;
    END IF;
  END PROCESS mergedDelay_reginc_process;


  mergedDelay_regout_unsigned <= unsigned(mergedDelay_regout);

  -- Output register for RAM-based shift register mergedDelay
  mergedDelay_regoutc_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        mergedOutput <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        mergedOutput <= mergedDelay_regout_unsigned;
      END IF;
    END IF;
  END PROCESS mergedDelay_regoutc_process;


  slicedInput <= mergedOutput(15 DOWNTO 8);

  Line_buffer_out1 <= slicedInput;

  out_4 <= std_logic_vector(Line_buffer_out1);

  out_5 <= std_logic_vector(Delay2_out1);

  out_6 <= std_logic_vector(Delay5_out1);

  slicedInput_1 <= mergedOutput(7 DOWNTO 0);

  Line_buffer1_out1 <= slicedInput_1;

  out_7 <= std_logic_vector(Line_buffer1_out1);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay3_out1 <= Line_buffer1_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  out_8 <= std_logic_vector(Delay3_out1);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay6_out1 <= Delay3_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  out_9 <= std_logic_vector(Delay6_out1);

  out_1 <= channel_in;

END rtl;

