-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\rgbFilter_2024a\rgb_filte_ip_src_comparison2.vhd
-- Created: 2025-03-25 10:24:49
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rgb_filte_ip_src_comparison2
-- Source Path: rgbFilter_2024a/rgb_filter/Subsystem1/comparison2
-- Hierarchy Level: 2
-- Model version: 8.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rgb_filte_ip_src_comparison2 IS
  PORT( In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        In2                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END rgb_filte_ip_src_comparison2;


ARCHITECTURE rtl OF rgb_filte_ip_src_comparison2 IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL In2_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational_Operator_out1         : std_logic;
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  In1_unsigned <= unsigned(In1);

  In2_unsigned <= unsigned(In2);

  
  Relational_Operator_out1 <= '1' WHEN In1_unsigned <= In2_unsigned ELSE
      '0';

  Constant_out1 <= to_unsigned(16#00#, 8);

  
  Switch_out1 <= Constant_out1 WHEN Relational_Operator_out1 = '0' ELSE
      In1_unsigned;

  Out1 <= std_logic_vector(Switch_out1);

END rtl;

