open_system('gm_rgbFilter_2024a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1', 'user2');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1', 1, 1, 'cp : 1.973 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1', 'user2');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1', 0, 1, 'cp : 1.731 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/Delay2', 'user1');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/Delay2', 1, 1, 'cp : 1.973 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/Bit Concat', 'user2');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/Bit Concat', 0, 1, 'cp : 1.731 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/gray1', 'user1');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/gray1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1/Relational Operator', 'user2');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1/Relational Operator', 0, 1, 'cp : 1.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1/Switch', 'user2');
annotate_port('gm_rgbFilter_2024a/rgb_filter/Subsystem1/comparison1/Switch', 0, 1, 'cp : 1.731 ns');
