open_system('gm_sobelFilter2024a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/Subsystem1', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/Subsystem1', 0, 1, 'cp : 10.798 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/Subsystem1/Delay1', 'user1');
annotate_port('gm_sobelFilter2024a/conv_core/Subsystem1/Delay1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/Subsystem1/Delay2', 'user1');
annotate_port('gm_sobelFilter2024a/conv_core/Subsystem1/Delay2', 1, 1, 'cp : 10.798 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/Subsystem1/Bit Concat', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/Subsystem1/Bit Concat', 0, 1, 'cp : 10.556 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/Subsystem1/Sum of Elements', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/Subsystem1/Sum of Elements', 0, 1, 'cp : 10.556 ns');
