-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\rgbFilter_2024a\rgb_filte_ip_addr_decoder.vhd
-- Created: 2025-03-25 10:25:06
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rgb_filte_ip_addr_decoder
-- Source Path: rgb_filte_ip/rgb_filte_ip_axi_lite/rgb_filte_ip_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rgb_filte_ip_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_axi4_stream_video_slave_image_width :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        write_axi4_stream_video_slave_image_height :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        write_axi4_stream_video_slave_hporch :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        write_axi4_stream_video_slave_vporch :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        write_red                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        write_green                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        write_blue                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END rgb_filte_ip_addr_decoder;


ARCHITECTURE rtl OF rgb_filte_ip_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_blue_1_1              : std_logic;  -- ufix1
  SIGNAL decode_sel_green_1_1             : std_logic;  -- ufix1
  SIGNAL decode_sel_red_1_1               : std_logic;  -- ufix1
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL decode_sel_axi4_stream_video_slave_vporch_1_1 : std_logic;  -- ufix1
  SIGNAL decode_sel_axi4_stream_video_slave_hporch_1_1 : std_logic;  -- ufix1
  SIGNAL decode_sel_axi4_stream_video_slave_image_height_1_1 : std_logic;  -- ufix1
  SIGNAL decode_sel_axi4_stream_video_slave_image_width_1_1 : std_logic;  -- ufix1
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL const_1_1                        : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL data_slice_axi_enable_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi_enable_1_1         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi4_stream_video_slave_image_width_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_axi4_stream_video_slave_image_width : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_reg_axi4_stream_video_slave_image_width_1_1 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_slice_axi4_stream_video_slave_image_width_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi4_stream_video_slave_image_width_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi4_stream_video_slave_image_height_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_axi4_stream_video_slave_image_height : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_reg_axi4_stream_video_slave_image_height_1_1 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_slice_axi4_stream_video_slave_image_height_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi4_stream_video_slave_image_height_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi4_stream_video_slave_hporch_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_axi4_stream_video_slave_hporch : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_reg_axi4_stream_video_slave_hporch_1_1 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_slice_axi4_stream_video_slave_hporch_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi4_stream_video_slave_hporch_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi4_stream_video_slave_vporch_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_axi4_stream_video_slave_vporch : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_reg_axi4_stream_video_slave_vporch_1_1 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL data_slice_axi4_stream_video_slave_vporch_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi4_stream_video_slave_vporch_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_red_1_1                  : std_logic;  -- ufix1
  SIGNAL data_in_red                      : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_reg_red_1_1                 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_slice_red_1                 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_red_1_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_green_1_1                : std_logic;  -- ufix1
  SIGNAL data_in_green                    : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_reg_green_1_1               : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_slice_green_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_green_1_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_blue_1_1                 : std_logic;  -- ufix1
  SIGNAL data_in_blue                     : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_reg_blue_1_1                : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_slice_blue_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_blue_1_1               : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_blue_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  
  decode_sel_green_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  
  decode_sel_red_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0006#, 14) ELSE
      '0';

  
  decode_sel_axi4_stream_video_slave_vporch_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0005#, 14) ELSE
      '0';

  
  decode_sel_axi4_stream_video_slave_hporch_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0004#, 14) ELSE
      '0';

  
  decode_sel_axi4_stream_video_slave_image_height_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0003#, 14) ELSE
      '0';

  
  decode_sel_axi4_stream_video_slave_image_width_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  const_1_1 <= '1';

  enb <= const_1_1;

  reg_axi_enable_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_axi_enable_1_1 <= '1';
      ELSIF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  data_slice_axi_enable_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & data_reg_axi_enable_1_1;

  
  decode_rd_axi_enable_1_1 <= const_0 WHEN decode_sel_axi_enable_1_1 = '0' ELSE
      data_slice_axi_enable_1;

  reg_enb_axi4_stream_video_slave_image_width_1_1 <= decode_sel_axi4_stream_video_slave_image_width_1_1 AND wr_enb;

  data_in_axi4_stream_video_slave_image_width <= data_write_unsigned(12 DOWNTO 0);

  reg_axi4_stream_video_slave_image_width_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_axi4_stream_video_slave_image_width_1_1 <= to_unsigned(16#0780#, 13);
      ELSIF enb = '1' AND reg_enb_axi4_stream_video_slave_image_width_1_1 = '1' THEN
        data_reg_axi4_stream_video_slave_image_width_1_1 <= data_in_axi4_stream_video_slave_image_width;
      END IF;
    END IF;
  END PROCESS reg_axi4_stream_video_slave_image_width_1_1_process;


  data_slice_axi4_stream_video_slave_image_width_1 <= resize(data_reg_axi4_stream_video_slave_image_width_1_1, 32);

  
  decode_rd_axi4_stream_video_slave_image_width_1_1 <= decode_rd_axi_enable_1_1 WHEN decode_sel_axi4_stream_video_slave_image_width_1_1 = '0' ELSE
      data_slice_axi4_stream_video_slave_image_width_1;

  reg_enb_axi4_stream_video_slave_image_height_1_1 <= decode_sel_axi4_stream_video_slave_image_height_1_1 AND wr_enb;

  data_in_axi4_stream_video_slave_image_height <= data_write_unsigned(12 DOWNTO 0);

  reg_axi4_stream_video_slave_image_height_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_axi4_stream_video_slave_image_height_1_1 <= to_unsigned(16#0438#, 13);
      ELSIF enb = '1' AND reg_enb_axi4_stream_video_slave_image_height_1_1 = '1' THEN
        data_reg_axi4_stream_video_slave_image_height_1_1 <= data_in_axi4_stream_video_slave_image_height;
      END IF;
    END IF;
  END PROCESS reg_axi4_stream_video_slave_image_height_1_1_process;


  data_slice_axi4_stream_video_slave_image_height_1 <= resize(data_reg_axi4_stream_video_slave_image_height_1_1, 32);

  
  decode_rd_axi4_stream_video_slave_image_height_1_1 <= decode_rd_axi4_stream_video_slave_image_width_1_1 WHEN decode_sel_axi4_stream_video_slave_image_height_1_1 = '0' ELSE
      data_slice_axi4_stream_video_slave_image_height_1;

  reg_enb_axi4_stream_video_slave_hporch_1_1 <= decode_sel_axi4_stream_video_slave_hporch_1_1 AND wr_enb;

  data_in_axi4_stream_video_slave_hporch <= data_write_unsigned(12 DOWNTO 0);

  reg_axi4_stream_video_slave_hporch_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_axi4_stream_video_slave_hporch_1_1 <= to_unsigned(16#0118#, 13);
      ELSIF enb = '1' AND reg_enb_axi4_stream_video_slave_hporch_1_1 = '1' THEN
        data_reg_axi4_stream_video_slave_hporch_1_1 <= data_in_axi4_stream_video_slave_hporch;
      END IF;
    END IF;
  END PROCESS reg_axi4_stream_video_slave_hporch_1_1_process;


  data_slice_axi4_stream_video_slave_hporch_1 <= resize(data_reg_axi4_stream_video_slave_hporch_1_1, 32);

  
  decode_rd_axi4_stream_video_slave_hporch_1_1 <= decode_rd_axi4_stream_video_slave_image_height_1_1 WHEN decode_sel_axi4_stream_video_slave_hporch_1_1 = '0' ELSE
      data_slice_axi4_stream_video_slave_hporch_1;

  reg_enb_axi4_stream_video_slave_vporch_1_1 <= decode_sel_axi4_stream_video_slave_vporch_1_1 AND wr_enb;

  data_in_axi4_stream_video_slave_vporch <= data_write_unsigned(12 DOWNTO 0);

  reg_axi4_stream_video_slave_vporch_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_axi4_stream_video_slave_vporch_1_1 <= to_unsigned(16#002D#, 13);
      ELSIF enb = '1' AND reg_enb_axi4_stream_video_slave_vporch_1_1 = '1' THEN
        data_reg_axi4_stream_video_slave_vporch_1_1 <= data_in_axi4_stream_video_slave_vporch;
      END IF;
    END IF;
  END PROCESS reg_axi4_stream_video_slave_vporch_1_1_process;


  data_slice_axi4_stream_video_slave_vporch_1 <= resize(data_reg_axi4_stream_video_slave_vporch_1_1, 32);

  
  decode_rd_axi4_stream_video_slave_vporch_1_1 <= decode_rd_axi4_stream_video_slave_hporch_1_1 WHEN decode_sel_axi4_stream_video_slave_vporch_1_1 = '0' ELSE
      data_slice_axi4_stream_video_slave_vporch_1;

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  reg_ip_timestamp_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        read_reg_ip_timestamp <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= decode_rd_axi4_stream_video_slave_vporch_1_1 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_enb_red_1_1 <= decode_sel_red_1_1 AND wr_enb;

  data_in_red <= data_write_unsigned(7 DOWNTO 0);

  reg_red_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_red_1_1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' AND reg_enb_red_1_1 = '1' THEN
        data_reg_red_1_1 <= data_in_red;
      END IF;
    END IF;
  END PROCESS reg_red_1_1_process;


  data_slice_red_1 <= resize(data_reg_red_1_1, 32);

  
  decode_rd_red_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_red_1_1 = '0' ELSE
      data_slice_red_1;

  reg_enb_green_1_1 <= decode_sel_green_1_1 AND wr_enb;

  data_in_green <= data_write_unsigned(7 DOWNTO 0);

  reg_green_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_green_1_1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' AND reg_enb_green_1_1 = '1' THEN
        data_reg_green_1_1 <= data_in_green;
      END IF;
    END IF;
  END PROCESS reg_green_1_1_process;


  data_slice_green_1 <= resize(data_reg_green_1_1, 32);

  
  decode_rd_green_1_1 <= decode_rd_red_1_1 WHEN decode_sel_green_1_1 = '0' ELSE
      data_slice_green_1;

  reg_enb_blue_1_1 <= decode_sel_blue_1_1 AND wr_enb;

  data_in_blue <= data_write_unsigned(7 DOWNTO 0);

  reg_blue_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_blue_1_1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' AND reg_enb_blue_1_1 = '1' THEN
        data_reg_blue_1_1 <= data_in_blue;
      END IF;
    END IF;
  END PROCESS reg_blue_1_1_process;


  data_slice_blue_1 <= resize(data_reg_blue_1_1, 32);

  
  decode_rd_blue_1_1 <= decode_rd_green_1_1 WHEN decode_sel_blue_1_1 = '0' ELSE
      data_slice_blue_1;

  data_read <= std_logic_vector(decode_rd_blue_1_1);

  write_axi4_stream_video_slave_image_width <= std_logic_vector(data_reg_axi4_stream_video_slave_image_width_1_1);

  write_axi4_stream_video_slave_image_height <= std_logic_vector(data_reg_axi4_stream_video_slave_image_height_1_1);

  write_axi4_stream_video_slave_hporch <= std_logic_vector(data_reg_axi4_stream_video_slave_hporch_1_1);

  write_axi4_stream_video_slave_vporch <= std_logic_vector(data_reg_axi4_stream_video_slave_vporch_1_1);

  write_red <= std_logic_vector(data_reg_red_1_1);

  write_green <= std_logic_vector(data_reg_green_1_1);

  write_blue <= std_logic_vector(data_reg_blue_1_1);

  write_axi_enable <= data_reg_axi_enable_1_1;

END rtl;

