# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/constraints.xdc

# Block Designs: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_1_0 || ORIG_REF_NAME==design_1_axi_vdma_1_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_2_0 || ORIG_REF_NAME==design_1_axi_vdma_2_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_3_0/design_1_axi_vdma_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_3_0 || ORIG_REF_NAME==design_1_axi_vdma_3_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_cam_axi_1_0/design_1_cam_axi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cam_axi_1_0 || ORIG_REF_NAME==design_1_cam_axi_1_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_cam_axi_2_0/design_1_cam_axi_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cam_axi_2_0 || ORIG_REF_NAME==design_1_cam_axi_2_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_read_trigger_0_0/design_1_read_trigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_read_trigger_0_0 || ORIG_REF_NAME==design_1_read_trigger_0_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_1_0 || ORIG_REF_NAME==design_1_smartconnect_1_0} -quiet] -quiet

# Block Designs: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/bd_88fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_0/bd_88fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/bd_88fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/bd_88fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/bd_88fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/bd_88fd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/bd_88fd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/bd_88fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_conv_core_ip_0_0/design_1_conv_core_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conv_core_ip_0_0 || ORIG_REF_NAME==design_1_conv_core_ip_0_0} -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_1_0 || ORIG_REF_NAME==design_1_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_1_0 || ORIG_REF_NAME==design_1_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_2_0 || ORIG_REF_NAME==design_1_axi_vdma_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_2_0 || ORIG_REF_NAME==design_1_axi_vdma_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_3_0/design_1_axi_vdma_3_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_3_0 || ORIG_REF_NAME==design_1_axi_vdma_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_3_0/design_1_axi_vdma_3_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_3_0 || ORIG_REF_NAME==design_1_axi_vdma_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axi_vdma_3_0/design_1_axi_vdma_3_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sawn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_swn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sbn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_s01a2s_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sarn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_srn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00s2a_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00arn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00rn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m00awn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m00wn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m00bn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_s00a2s_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_sawn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/bd_88fd_swn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/bd_88fd_sbn_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/bd_88fd_m00s2a_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_smartconnect_1_0/ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc

# XDC: c:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc

# XDC: C:/dkaputa/courses/563-embeddesSystemsDesignTwo_2025/lecture14/referenceDesign/hdl_prj/vivado_ip_prj/src/design_1/design_1_ooc.xdc
