-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\rgbFilter_2024a\rgb_filte_ip_src_rgb_filter.vhd
-- Created: 2025-03-25 10:24:49
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.77039e-06
-- Target subsystem base rate: 2.77039e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.77039e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Video_out                     ce_out        2.77039e-06
-- valid_out_hStart              ce_out        2.77039e-06
-- valid_out_hEnd                ce_out        2.77039e-06
-- valid_out_vStart              ce_out        2.77039e-06
-- valid_out_vEnd                ce_out        2.77039e-06
-- valid_out_valid               ce_out        2.77039e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rgb_filte_ip_src_rgb_filter
-- Source Path: rgbFilter_2024a/rgb_filter
-- Hierarchy Level: 0
-- Model version: 8.0
-- 
-- Simulink model description for rgbFilter_2024a:
-- 
-- Sobel Edge Detection Using the MATLAB(R) Function Block
-- This example shows how to use HDL Coder(TM) to check, 
-- generate, and verify HDL code for a Sobel Edge Detection 
-- block built using the MATLAB Function block.
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rgb_filte_ip_src_rgb_filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        red                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        green                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        blue                              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_in                          :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        ctrl_hStart                       :   IN    std_logic;
        ctrl_hEnd                         :   IN    std_logic;
        ctrl_vStart                       :   IN    std_logic;
        ctrl_vEnd                         :   IN    std_logic;
        ctrl_valid                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Video_out                         :   OUT   std_logic_vector(63 DOWNTO 0);  -- ufix64
        valid_out_hStart                  :   OUT   std_logic;
        valid_out_hEnd                    :   OUT   std_logic;
        valid_out_vStart                  :   OUT   std_logic;
        valid_out_vEnd                    :   OUT   std_logic;
        valid_out_valid                   :   OUT   std_logic
        );
END rgb_filte_ip_src_rgb_filter;


ARCHITECTURE rtl OF rgb_filte_ip_src_rgb_filter IS

  -- Component Declarations
  COMPONENT rgb_filte_ip_src_Subsystem1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In2                             :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          red                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          green                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          blue                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Enable                          :   IN    std_logic;
          Video_out                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : rgb_filte_ip_src_Subsystem1
    USE ENTITY work.rgb_filte_ip_src_Subsystem1(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL valid                            : std_logic;
  SIGNAL Subsystem1_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subsystem1_out1_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Concat1_out1                 : unsigned(63 DOWNTO 0);  -- ufix64
  SIGNAL Delay1_out1_hStart               : std_logic;
  SIGNAL Delay1_out1_hEnd                 : std_logic;
  SIGNAL Delay1_out1_vStart               : std_logic;
  SIGNAL Delay1_out1_vEnd                 : std_logic;
  SIGNAL Delay1_out1_valid                : std_logic;

BEGIN
  u_Subsystem1 : rgb_filte_ip_src_Subsystem1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In2 => Video_in,  -- ufix64
              red => red,  -- uint8
              green => green,  -- uint8
              blue => blue,  -- uint8
              Enable => valid,
              Video_out => Subsystem1_out1  -- uint32
              );

  valid <= ctrl_valid;

  Subsystem1_out1_unsigned <= unsigned(Subsystem1_out1);

  Bit_Concat1_out1 <= Subsystem1_out1_unsigned & Subsystem1_out1_unsigned;

  Video_out <= std_logic_vector(Bit_Concat1_out1);

  enb <= clk_enable;

  c_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_hStart <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_hStart <= ctrl_hStart;
      END IF;
    END IF;
  END PROCESS c_process;


  c_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_hEnd <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_hEnd <= ctrl_hEnd;
      END IF;
    END IF;
  END PROCESS c_1_process;


  c_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_vStart <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_vStart <= ctrl_vStart;
      END IF;
    END IF;
  END PROCESS c_2_process;


  c_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_vEnd <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_vEnd <= ctrl_vEnd;
      END IF;
    END IF;
  END PROCESS c_3_process;


  c_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_valid <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_valid <= ctrl_valid;
      END IF;
    END IF;
  END PROCESS c_4_process;


  ce_out <= clk_enable;

  valid_out_hStart <= Delay1_out1_hStart;

  valid_out_hEnd <= Delay1_out1_hEnd;

  valid_out_vStart <= Delay1_out1_vStart;

  valid_out_vEnd <= Delay1_out1_vEnd;

  valid_out_valid <= Delay1_out1_valid;

END rtl;

