-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\rgbFilter_2024a\rgb_filte_ip_src_Subsystem1.vhd
-- Created: 2025-03-25 10:24:49
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rgb_filte_ip_src_Subsystem1
-- Source Path: rgbFilter_2024a/rgb_filter/Subsystem1
-- Hierarchy Level: 1
-- Model version: 8.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rgb_filte_ip_src_Subsystem1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In2                               :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        red                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        green                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        blue                              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Enable                            :   IN    std_logic;
        Video_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END rgb_filte_ip_src_Subsystem1;


ARCHITECTURE rtl OF rgb_filte_ip_src_Subsystem1 IS

  -- Component Declarations
  COMPONENT rgb_filte_ip_src_comparison
    PORT( In1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          In2                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT rgb_filte_ip_src_comparison1
    PORT( In1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          In2                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT rgb_filte_ip_src_comparison2
    PORT( In1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          In2                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : rgb_filte_ip_src_comparison
    USE ENTITY work.rgb_filte_ip_src_comparison(rtl);

  FOR ALL : rgb_filte_ip_src_comparison1
    USE ENTITY work.rgb_filte_ip_src_comparison1(rtl);

  FOR ALL : rgb_filte_ip_src_comparison2
    USE ENTITY work.rgb_filte_ip_src_comparison2(rtl);

  -- Signals
  SIGNAL enb_gated                        : std_logic;
  SIGNAL alphavalid                       : std_logic;
  SIGNAL In2_unsigned                     : unsigned(63 DOWNTO 0);  -- ufix64
  SIGNAL slice_1_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL comparison_out1                  : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL comparison_out1_unsigned         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL gray1_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL comparison1_out1                 : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL comparison1_out1_unsigned        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL gray2_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL comparison2_out1                 : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL comparison2_out1_unsigned        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL y                                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay2_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay2_out1_bypass               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay2_out1_last_value           : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  -- slice out red
  -- slice out green
  -- slice out blue

  u_comparison : rgb_filte_ip_src_comparison
    PORT MAP( In1 => std_logic_vector(slice_1_out1),  -- uint8
              In2 => red,  -- uint8
              Out1 => comparison_out1  -- uint8
              );

  u_comparison1 : rgb_filte_ip_src_comparison1
    PORT MAP( In1 => std_logic_vector(gray1_out1),  -- uint8
              In2 => green,  -- uint8
              Out1 => comparison1_out1  -- uint8
              );

  u_comparison2 : rgb_filte_ip_src_comparison2
    PORT MAP( In1 => std_logic_vector(gray2_out1),  -- uint8
              In2 => blue,  -- uint8
              Out1 => comparison2_out1  -- uint8
              );

  alphavalid <= Enable;

  enb_gated <= alphavalid AND enb;

  In2_unsigned <= unsigned(In2);

  slice_1_out1 <= In2_unsigned(23 DOWNTO 16);

  comparison_out1_unsigned <= unsigned(comparison_out1);

  gray1_out1 <= In2_unsigned(15 DOWNTO 8);

  comparison1_out1_unsigned <= unsigned(comparison1_out1);

  gray2_out1 <= In2_unsigned(7 DOWNTO 0);

  comparison2_out1_unsigned <= unsigned(comparison2_out1);

  y <= comparison_out1_unsigned & comparison_out1_unsigned & comparison1_out1_unsigned & comparison2_out1_unsigned;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= to_unsigned(0, 32);
      ELSIF enb_gated = '1' THEN
        Delay2_out1 <= y;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Video_out_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1_last_value <= to_unsigned(0, 32);
      ELSIF enb_gated = '1' THEN
        Delay2_out1_last_value <= Delay2_out1_bypass;
      END IF;
    END IF;
  END PROCESS Video_out_bypass_process;


  
  Delay2_out1_bypass <= Delay2_out1_last_value WHEN alphavalid = '0' ELSE
      Delay2_out1;

  Video_out <= std_logic_vector(Delay2_out1_bypass);

END rtl;

